
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ELSE ID IF LCUR LP OP1 OP2 OP3 OP6 RCUR RP S1 S2 VAL semicolonS : IF LP C RP LCUR S1 semicolon RCUR ELSE LCUR S2 semicolon RCURC : ID OP1 OP2 VAL\n        | ID OP2 OP2 VAL\n        | ID OP3 OP2 VAL\n        | ID OP6 OP2 VAL\n        | ID OP3 VAL\n        | ID OP6 VAL'
    
_lr_action_items = {'IF':([0,],[2,]),'$end':([1,29,],[0,-1,]),'LP':([2,],[3,]),'ID':([3,],[5,]),'RP':([4,15,17,19,20,21,22,],[6,-6,-7,-2,-3,-4,-5,]),'OP1':([5,],[7,]),'OP2':([5,7,8,9,10,],[8,12,13,14,16,]),'OP3':([5,],[9,]),'OP6':([5,],[10,]),'LCUR':([6,25,],[11,26,]),'VAL':([9,10,12,13,14,16,],[15,17,19,20,21,22,]),'S1':([11,],[18,]),'semicolon':([18,27,],[23,28,]),'RCUR':([23,28,],[24,29,]),'ELSE':([24,],[25,]),'S2':([26,],[27,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'C':([3,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> IF LP C RP LCUR S1 semicolon RCUR ELSE LCUR S2 semicolon RCUR','S',13,'p_if','afll.py',28),
  ('C -> ID OP1 OP2 VAL','C',4,'p_C','afll.py',32),
  ('C -> ID OP2 OP2 VAL','C',4,'p_C','afll.py',33),
  ('C -> ID OP3 OP2 VAL','C',4,'p_C','afll.py',34),
  ('C -> ID OP6 OP2 VAL','C',4,'p_C','afll.py',35),
  ('C -> ID OP3 VAL','C',3,'p_C','afll.py',36),
  ('C -> ID OP6 VAL','C',3,'p_C','afll.py',37),
]
